name: mp3tuneup-frontend
serviceType: web
region: oregon
plan: free
buildCommand: npm install && npm run build
startCommand: npm start
envVars:
  - key: NODE_ENV
    value: production
  - key: BACKEND_URL
    value: https://mp3tuneup-backend.onrender.com
  - key: NEXT_PUBLIC_APP_NAME
    value: mp3TuneUp